name = "Choo-Choo Charles - Enhanced"
display_name = "Choo-Choo Charles Enhanced"
default_url = "https://github.com/lgbarrere/Archipelago-Fork/releases/download/cccharles_enhanced_v{{version}}/cccharles_enhanced.apworld"

[versions]
"1.0.3" ={}