name = "Clair Obscur Expedition 33"
display_name = "Clair Obscur: Expedition 33"
default_url = "https://github.com/Demorck/ClairObscur_APWorld/releases/download/v{{version}}/clair_obscur.apworld"

[versions]
"0.2.1" ={}
