name = "CrossCode"
home = "https://discord.com/channels/731205301247803413/1128180904926396437"
default_url = "https://github.com/CodeTriangle/CCMultiworldRandomizer/releases/download/{{version}}/crosscode.apworld"

[versions]
"0.7.7" = {}
"0.7.8" = {}
"0.8.0" = {}
"0.8.1" = {}
"0.8.2" = {}
"0.8.3" = {}
"0.8.4" = {}
"0.8.5" = {}
# "0.9.0" = {} skipped due to generation failures
"0.9.1" = {}
"0.9.2" = {}
"0.9.3" = {}
"0.9.4" = {}
"0.9.6" = {}
