name = "Nine Sols"
home = "https://discord.com/channels/731205301247803413/1291949699150123048"
default_url = "https://github.com/Ixrec/NineSolsArchipelagoRandomizer/releases/download/{{version}}/nine_sols.apworld"

[versions]
"0.1.1" = {}
"0.1.4" = {}
"0.1.6" = {}
"0.2.1" = {}
"0.3.6" = {}
"0.4.3" = {}
"0.4.4" = {}
"0.4.6" = {}
"0.5.1" = {}
"0.5.3" = {}
"0.6.1" = {}
