name = "New Super Mario Bros. DS"
home = "https://discord.com/channels/731205301247803413/1389178071873097770"
default_url = "https://github.com/Lemix028/Archipelago-NewSuperMarioBrosDS/releases/download/nsmbds-v{{version}}-unstable/nsmbds.apworld"

[versions]
"0.5.0" = {}
