name = "Pokemon HeartGold and SoulSilver"
home = "https://discord.com/channels/731205301247803413/1541233325572759643"
default_url = "https://github.com/ljtpetersen/hgss_archipelago/releases/download/v{{version}}/pokemon_hgss.apworld"

[versions]
"0.0.6" = {}
