name = "Plants vs. Zombies"
display_name = "Plants vs. Zombies Replanted and GOTY"
home = "https://discord.com/channels/731205301247803413/1437352496455483413"
default_url = "https://github.com/dannybonz/replanted_archipelago/releases/download/v{{version}}/pvzr.apworld"

[versions]
"1.6.2" = {}
"1.6.3" = {}
"1.7.2" = {}
"1.8.0" = {}
"1.9.1" = {}
