name = "Symphony of the Night"
home = "https://discord.com/channels/731205301247803413/1108439196156317818"

[versions]
"0.81.4-alpha2" = { url = "https://github.com/fdelduque/Archipelago/releases/download/a08142/sotn.apworld" }
