name = "Tony Hawk's Pro Skater 1 + 2"
home = "https://discord.com/channels/731205301247803413/1349754176296583198"
default_url = "https://github.com/SerpentAI/Archipelago/releases/download/thps12-v{{version}}/tony_hawks_pro_skater_1_2.apworld"

[versions]
"1.2.0" = {}
"1.1.0" = { url = "https://github.com/SerpentAI/Archipelago/releases/download/thps12-v1.1.0/tony_hawks_pro_skater_1_2.apworld" }